version: '2.1'
services:
  jsonbox:
    container_name: jsonbox
    restart: always
    environment:
      - MONGODB_URI=mongodb://mongo:27017/jsonbox-io-dev
    build: .
    ports:
      - '3001:3000'
    network_mode: bridge
    mem_limit: 200M
